services:
  store-auth:
    image: eclipse-temurin:21-jdk-alpine
    container_name: store-auth
    hostname: store-auth
    ports:
      - "51720:51720"
    volumes:
    - ./:/app
    working_dir: /app
    command: ./gradlew bootRun
    depends_on:
      - store-auth-db
    networks:
      - store-network
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
        
  store-auth-db:
    image: postgres:18-alpine
    container_name: store-auth-db
    ports:
      - "51721:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: storeauthdb
    volumes:
      - store_auth_db_data:/var/lib/postgresql/data
    networks:
      - store-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d storeauthdb -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  store-auth-db-exporter:
    image: prometheuscommunity/postgres-exporter:v0.19.0
    container_name: store-auth-db-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:1@store-auth-db:5432/storeauthdb?sslmode=disable"
    depends_on:
      store-auth-db:
        condition: service_healthy
    networks:
      - store-network

networks:
  store-network:
    external: true

volumes:
  store_auth_db_data: