server:
  port: 51720

spring:
  threads:
    virtual:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: store-auth
  datasource:
    url: jdbc:postgresql://store-auth-db:5432/storeauthdb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: redis
      port: 6379
      password: 123456789qwerty123456789qwerty123456789qwerty #that password is just for local dev
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      compression-type: zstd
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false

jwt:
  issuer: axgiri@proton.me
  ttl-minutes: 15
  refresh-ttl-days: 30
  refresh-token-secret: 123456789qwerty123456789qwerty123456789qwerty
  public-key: classpath:keys/public.pem
  private-key: classpath:keys/private.pem

app:
  otp-ttl-minutes: 15
  kafka:
    topic:
      message: message-topic
    replicas: 3
    min-insync-replicas: 2
  
logging:
  level:
    root: INFO