spring:
  threads:
    virtual:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: oldlab-auth
  server:
    port: 51720
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD:1234567890abcdefghijklmnopqrstuvwxyz} #that password is just for local dev
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      compression-type: zstd
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false

jwt:
  issuer: oldlab-auth
  ttl-minutes: 15
  refresh-ttl-days: 30
  public-key: classpath:keys/public.pem
  private-key: classpath:keys/private.pem

app:
  otp-ttl-minutes: 15
  kafka:
    topic:
      message: message-topic
    replicas: 3
    min-insync-replicas: 2
  
